spring:
  datasource:
    url: jdbc:sqlite:identifier.sqlite?busy_timeout=5000
    hikari:
      connection-init-sql: PRAGMA busy_timeout = 5000;
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
#logging.level.org.hibernate.SQL: debug
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace
