packages:
  - .

allowBuilds:
  '@heroui/shared-utils': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  esbuild: true

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - 'sbuild'
  - 'esbuild'
